tags:
  - Tasks
summary: Delete task by ID
operationId: deleteTask
description: 'Remove specified task.'
security:
  - bearerAuth: []
parameters:
  - in: path
    name: taskId
    required: true
    schema:
      type: string
      example: '6727d414742499c95150c4fd'
      description: Unique identifier of the task
responses:
  '204':
    description: Successfully deleted
  '404':
    $ref: '../../../components/responses/404.yaml'
  '401':
    $ref: '../../../components/responses/401.yaml'
