tags:
  - Tasks
summary: Move task between columns
operationId: MoveTask
description:
  'Move a task from its current column to a specified target column within the
  same board.'
security:
  - bearerAuth: []
parameters:
  - in: path
    name: boardId
    required: true
    schema:
      type: string
      example: '6727df6c4b3492bdaa888f95'
      description: Unique identifier of the board
  - in: path
    name: columnId
    required: true
    schema:
      type: string
      example: '66f19ff0bcd4dd2171ec0d22'
      description: Unique identifier of the column
  - in: path
    name: taskId
    required: true
    schema:
      type: string
      example: '6727d414742499c95150c4fd'
      description: Unique identifier of the task
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        required:
          - newColumnId
        properties:
          newColumnId:
            description: 'Id of the column where task should be moved'
            type: string
            example: '6727d4f7742499c95150c521'
responses:
  '200':
    description: Successfully moved
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Task moved successfully!
            data:
              type: object
              $ref: '../../../components/schemas/task.yaml'
  '400':
    description: Bad Request
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 400
            message:
              type: string
              example: 'Task ID and new column ID are required'
  '401':
    $ref: '../../../components/responses/401.yaml'
  '404':
    $ref: ../../../components/responses/404.yaml
  '500':
    $ref: '../../../components/responses/500.yaml'
