openapi: 3.1.0
info:
  version: 1.0.0
  title: Task app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of task app
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: update user details and theme of app.
  - name: Help
    description: Send email to support.
  - name: Boards
    description: add, remove and update board for the authenticated user.
  - name: Columns
    description: add, remove and update column for the authenticated user.
  - name: Tasks
    description:
      add, remove, update and move (from one column to another) task for the
      authenticated user.
servers:
  - url: http://localhost:3000
  - url: https://task-pro-backend-mcfs.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/current.yaml
  /users/theme:
    patch:
      $ref: ../swagger/paths/users/theme.yaml
  /users/edit:
    patch:
      $ref: ../swagger/paths/users/edit.yaml
  /help:
    post:
      $ref: ../swagger/paths/help/help.yaml
  /boards:
    get:
      $ref: ../swagger/paths/boards/get.yaml
    post:
      $ref: ../swagger/paths/boards/post.yaml
  /boards/info:
    get:
      $ref: ../swagger/paths/boards/getInfo.yaml
  /boards/{boardId}:
    get:
      $ref: ../swagger/paths/boards/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/boards/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/boards/{id}/delete.yaml
  /boards/{boardId}/columns:
    post:
      $ref: ../swagger/paths/columns/post.yaml
  /boards/{boardId}/columns/{columnId}:
    patch:
      $ref: ../swagger/paths/columns/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/columns/{id}/delete.yaml
  /boards/{boardId}/columns/{columnId}/tasks:
    post:
      $ref: ../swagger/paths/tasks/post.yaml
  /boards/{boardId}/columns/{columnId}/tasks/{taskId}:
    patch:
      $ref: ../swagger/paths/tasks/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/tasks/{id}/delete.yaml
  /boards/{boardId}/columns/{columnId}/tasks/{taskId}/move:
    patch:
      $ref: ../swagger/paths/tasks/{id}/move.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
