openapi: 3.1.0
info:
  version: 1.0.0
  title: Task app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of task app
tags:
  - name: Task
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /task:
    get:
      $ref: ../swagger/paths/tasks/get.yaml
    post:
      $ref: ../swagger/paths/tasks/post.yaml
  /task/{id}:
    get:
      $ref: ../swagger/paths/tasks/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/tasks/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/tasks/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
